"""Custom errors.
"""

class EgyszerException(Exception):
    def __init__(self):
        pass
